org.gradle.jvmargs=-Xmx1024G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
kotlin.incremental=false
kotlin.daemon.jvmargs = Xmx2048M




# org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError

# kotlin.incremental=true
# kotlin.incremental.useClasspathSnapshot=true

# org.gradle.caching=true
# org.gradle.parallel=true
# org.gradle.vfs.watch=true

# kotlin.daemon.jvmargs=-Xmx2048m

# android.useAndroidX=true
# android.enableJetifier=true
# android.newDsl=false
# android.builtInKotlin=false